project(wpf_controls LANGUAGES CSharp)

add_library(wpf_controls SHARED
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_playback/animation_item_name_view.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_playback/animation_item_view.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_playback/animation_playback_panel.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/color_picker/color_palette.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/color_picker/dialog.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/color_picker/hue_spectrum.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/color_ramp.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/hypergraph_control.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/link/link.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/node/properties_node.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/link/link_point.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/logic_view/event_control.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/logic_view/logic_view.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/logic_view/logic_entity_view.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/boolean_editor.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/control_editor.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/combo_box_editor.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/enum_editor.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/ruler.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/default_editor.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/external_editor.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/i_list_collection_editor.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/int32_editor.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/properties_collection_editor.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/single_editor.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/string_select_file_editor.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/time_layout/time_layout.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/time_layout/time_layout_item_control.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/visual_curve.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/visual_curve_key.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/visual_curve_key_tangent.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/panel.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_lexeme_panel/animation_interval_item.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_lexeme_panel/animation_interval_view.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_lexeme_panel/animation_item.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_lexeme_panel/animation_item_intervals_view.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_lexeme_panel/animation_item_name_view.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_lexeme_panel/animation_lexeme_item.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_lexeme_panel/animation_lexeme_item_view.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_lexeme_panel/animation_lexeme_panel.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_lexeme_panel/animation_lexeme_panel_host.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_playback/animation_event.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_playback/animation_item_name_view.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_playback/animation_item_view.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_playback/animation_item.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_playback/animation_playback_host.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_playback/animation_playback_panel.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/animation_channel.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/animation_channel_item.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/animation_channel_type.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/animation_channel_list_view.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/animation_channel_name_view.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/event/animation_channel_event.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/event/animation_channel_events_view.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/event/animation_channel_event_view.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/interval/animation_channel_intervals_view.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/interval/animation_channel_interval_view.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/interval/animation_channel_interval.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/partition/animation_channel_partition.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/partition/animation_channel_partitions_view.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/partition/animation_channel_partition_type.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/partition/animation_channel_partition_type_to_visibility_converter.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/partition/animation_channel_partition_view.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/animation_setup_host.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/animation_setup_panel.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/setup_panel_event_args.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/animation_curve_editor.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/panel_curve_item.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/color_picker/color_workers/multiply_worker.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/data_sources/data_sources_panel.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/data_sources/data_source_item.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/data_sources/data_sources_panel_host.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/link/links_event_args.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/link/link_event_args.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/link/link_id.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/selection_event_args.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/markup_extensions/template_from_type_ext.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/color_matrix_editor.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/color_curve.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/color_curve_key.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/color_picker/color_to_hue_part_converter.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/color_picker/color_workers/alpha_worker.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/color_picker/color_workers/blue_worker.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/color_picker/color_workers/brightness_worker.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/color_picker/color_workers/green_worker.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/color_picker/color_workers/hue_worker.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/color_picker/color_workers/red_worder.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/color_picker/color_workers/saturation_worker.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/color_picker/color_rgb_component_extracter.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/color_matrix_editor/color_matrix_control.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/color_matrix_editor/control_point.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/color_matrix_editor/gradient_rect.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/color_matrix_editor/shaders/color_interpolation_effect.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/color_matrix_editor/shaders/utils.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/panels/linear_layout_panel.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/panels/scale_to_fit_control.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/panels/single_place_panel.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/color_matrix.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/color_matrix_element.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/color_rgb.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/color_utilities.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/color_picker/color_palette.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/color_picker/dialog.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/color_hsv.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/color_picker/hsv_circle.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/color_picker/hue_spectrum.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/command.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/converters/color_to_brush_converter.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/converters/bool_to_int_converter.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/converters/bool_to_visibility_converter.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/converters/Double_to_String_converter.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/converters/Point_to_String_converter.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/converters/singles_to_thickness_converter.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/converters/single_to_thickness_converter.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/helpers/dot_net_helpers.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/commands/link_command.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/commands/node_create_command.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/commands/node_move_command.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/commands/node_remove_command.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/commands/unlink_command.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/field.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/hypergraph_control.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/hypergraph_host.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/menu_event_args.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/graph.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/graph_edge.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/graph_node.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/i_caster.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/i_command.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/i_command_engine.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/link/link.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/node/properties_node.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/node/node_event_args.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/node/property.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/link/link_point.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/panels/scroll_viewer.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/node/node_property_attribute.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/logic_view/event_control.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/logic_view/logic_view.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/logic_view/logic_entity_view.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/logic_view/logic_view_host.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/markup_extensions/static_property_ext.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property/property_container_base.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property/property_container_collection.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/attributes/collection_attribute.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/color_ramp.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/converters/number_to_double_converter.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/converters/Enum_to_String_converter.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property/dictionary_item_property_value.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property/i_property_container.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property/i_property_info_value.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property/object_property_value.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property/property_container.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property/property_descriptor.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property/i_property_value.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property/callback_property_value.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property/property_property_value.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/attributes/combo_box_items_attribute.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/attributes/data_source_attribute.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/attributes/value_range_and_format_attribute.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/attributes/vector3_attribute.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/browsable_state.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/default_editors_lists.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/property.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/assignable_type_editor_picker.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/attributes/material_stage_effect_holder_attribute.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/attribute_editor_picker.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/attributes/control_container_attribute.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/property_editor_base.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/property_extractor.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/editor_picker.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/boolean_editor.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/control_editor.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/color_curve_editor.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/float_curve_editor.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/value_collection_editor_base.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/combo_box_editor.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/default_editor.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/value_editor_base.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/enum_editor.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/external_editor.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/i_list_collection_editor.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/int32_editor.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/properties_collection_editor.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/single_editor.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/string_select_file_editor.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/attributes/external_editor_attribute.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/item/item_editor_base.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value_editor_selector.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/empty_collection_checher.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/attributes/expandable_item_attribute.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/property_grid/host.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/item_editor_selector.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/item_property_descriptor.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/i_external_property_editor.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/attributes/String_select_file_editor_attribute.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/type_editor_picker.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/settings.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/time_layout/time_layout_parent_length_time_converter.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/time_layout/time_layout_parent_length_value_validation_rule.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/time_layout/time_layout_end_value_validation_rule.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/time_layout/time_layout_length_value_validation_rule.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/time_layout/time_layout_length_time_converter.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/float_curve/float_curve.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/converters/main_dock_panel_width_converter.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/time_layout/time_layout_end_time_converter.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/ruler.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/time_layout/time_layout_scale_dependent_converter.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/time_layout/time_layout_start_time_converter.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/time_layout/time_layout_host.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/time_layout/time_layout_host.Designer.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/time_layout/time_layout_item.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/time_layout/time_layout.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/time_layout/time_layout_item_control.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/time_layout/time_layout_item_template_selector.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/time_layout/time_layout_start_value_validation_rule.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/float_curve/float_curve_key.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/float_curve/float_curve_key_type.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/Properties/AssemblyInfo.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/attributes/special_attribute.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/time_layout/time_layout_visibility_converter.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/converters/Vector3D_to_string_converter.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/select_behavior.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/sizeable_matrix.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/helpers/utils.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/helpers/utils_helpers.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/visual_curve.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/curves_link.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/hermite_spline_evaluator.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/visual_curve_key.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/visual_curve_key_tangent.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/panel.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/visual_curve_range.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/logic_view/logic_scenes_view.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/string_editor.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/themes/progress_bar_theme.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/themes/string_editor_theme.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/themes/value_editors_themes.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/effects/noise_effect/noise_effect_settings_window.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/panel_curve_group.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/animation_curve_editor.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/panel_curve_item.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_lexeme_panel/animation_item_intervals_view.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_lexeme_panel/animation_interval_view.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_lexeme_panel/animation_item_name_view.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_lexeme_panel/animation_lexeme_item_view.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_lexeme_panel/animation_lexeme_panel.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/color_picker/color_component_slider.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/color_picker/color_component_slider.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/color_picker/color_workers/color_part_worker_base.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/animation_channel_list_view.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/animation_channel_name_view.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/animation_setup_panel.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/event/animation_channel_events_view.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/event/animation_channel_event_view.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/interval/animation_channel_intervals_view.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/interval/animation_channel_interval_view.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/partition/animation_channel_partitions_view.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/animation_setup/channels/partition/animation_channel_partition_view.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/color_picker/hsv_circle.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/color_matrix_editor/color_matrix_control.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/color_matrix_editor/control_point.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/color_matrix_editor/gradient_rect.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/panel_curve_effect.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/templates/sqrt_curve_template.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/templates/sinusoid_curve_template.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/visual_curve_key_range_control.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/data_sources/data_sources_panel.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/data_sources/data_source_item.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/themes/editors_themes.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/themes/number_editor_theme.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/node_above_header_content/groups_editor_node_above_header_content.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/item/themes/custom_item_editor_theme.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/item/themes/data_source_editor_theme.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/item/themes/item_editor_themes.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/item/themes/material_stage_editor_theme.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/item/themes/material_stage_effect_editor_theme.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/item/themes/named_item_editor_theme.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/color_curve_editor.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/color_editor.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/color_matrix_editor.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/float_curve_editor.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/property_container_editor.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/text_box_editor_extension.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/vector3_editor.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/property_grid/property_grid_control.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/themes/expandable_items_control_theme.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/themes/generic.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/property_grid/themes/property_grid_item_theme.xaml"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/property_grid/property_grid_control.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/property_grid/host.Designer.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/property_grid/property.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/property_grid/category_group_description.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/color_picker/HueCircle.png"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/color_picker/Saturation.png"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/curves_panel.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/curves_panel_presenter.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/tools/add_tool.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/tools/move_range_tool.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/tools/move_tool.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/tools/remove_tool.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/tools/scale_tool.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/tools/tool_base.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/visual_curve_key_range_control.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/panel_curve_group.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/visual_curve_segment.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/helpers/grid_helper.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/link/can_link_event_args.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/node_above_header_content/groups_editor_node_above_header_content.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/node/node_move_event_args.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/node/property_view.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/input/input.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/input/input_command_event.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/library_initializer.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/helpers/math.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/attributes/custom_property_attribute.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/attributes/extension_attribute.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/attributes/text_box_extension_attribute.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/property_items_control.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/color_editor.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/property_container_editor.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/text_box_editor_extension.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/value_editor_extension_base.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/vector3_editor.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/icons/addkey.png"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/icons/focus.png"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/icons/focustodefaultrange.png"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/icons/movenodes.png"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/icons/moverange.png"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/icons/nodetype1.png"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/icons/nodetype2.png"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/icons/nodetype3.png"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/icons/nodetype4.png"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/icons/nodetype5.png"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/icons/removekey.png"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/icons/scalenodes.png"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/icons/snaptogrid.png"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/icons/snaptonodes.png"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/icons/togglerange0.png"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/icons/togglerange1.png"
					"${CMAKE_CURRENT_SOURCE_DIR}/../../WPFToolkit.Extended/WPFToolkit.Extended.csproj"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/panels/centralized_scroll_panel.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/node/node.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/node/properties_control.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/markup_extensions/this_ext.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/panels/i_centralized_control.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/attributes/color_curve_editor_attribute.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/attributes/float_curve_editor_attribute.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/property_grid/property_grid_item.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/property_grid/refresh_grid_on_change_attribute.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/property_grid/value_changed_event_args.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/property_grid/value_changed_event_handler.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/expandable_items_control.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/item/named_item_editor.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/item/custom_item_editor.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/item/data_source_editor.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/item/material_stage_editor.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/hypergraph/pan_direction.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/logic_view/logic_scenes_view.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/controls/property_grid/hierarchy_node.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/converters/color_to_string_converter.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/helpers/debug.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property/control_containers/button.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property/control_containers/control.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property/control_containers/control_container.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property/control_containers/dock_control_container.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property/control_containers/stack_control_container.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property/control_containers/toggle_button.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property/control_containers/uniform_control_container.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/attributes/control_attribute.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/item/control_container_editor.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/float_curve/float_curve_group.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/float_curve/float_curve_monotone_type.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/hermite_spline_evaluator.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/hierarchy_item_id.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/effects/visual_effect_base.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/effects/noise_effect/visual_noise_effect.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/effects/noise_effect/noise_effect_settings_window.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/panel_curve_effect.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/templates/curve_template_base.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/templates/custom_curve_template.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/templates/sqrt_curve_template.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/curve_editor/templates/sinusoid_curve_template.xaml.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/type_editors/number_editor.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/item/material_stage_effect_editor.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/float_curve/effects/float_curve_effect.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/float_curve/float_curve_evaluator.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/types/float_curve/effects/float_curve_noise_effect.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/attributes/type_converter.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/attributes/type_converter_attribute.cs"
					"${CMAKE_CURRENT_SOURCE_DIR}/property_editors/value/string_editor.xaml.cs"
)

set_target_properties(wpf_controls PROPERTIES FOLDER "engine/editors")
