add_subdirectory(ai)
add_subdirectory(ai_navigation)
add_subdirectory(animation)
add_subdirectory(client)
add_subdirectory(collision)
add_subdirectory(core)
add_subdirectory(debug)
add_subdirectory(engine)
#add_subdirectory(finger_printer)
add_subdirectory(fs)
add_subdirectory(fs_pack)
add_subdirectory(game)
add_subdirectory(game_server)
add_subdirectory(graphics_benchmark)
add_subdirectory(input)
add_subdirectory(lobby_server)
add_subdirectory(logging)
add_subdirectory(login_server)
add_subdirectory(maya)
add_subdirectory(maya_animation)
add_subdirectory(network)
add_subdirectory(particle)
add_subdirectory(physics)
add_subdirectory(render)
add_subdirectory(resources_performance_test)
add_subdirectory(rms_generator)
add_subdirectory(rtp)
add_subdirectory(rtp_learn)
#add_subdirectory(sample_rate_test)
add_subdirectory(shader_compiler)
add_subdirectory(shader_generator)
add_subdirectory(sound)
add_subdirectory(sound_system_usage_example)
add_subdirectory(test)
add_subdirectory(test_animations)
add_subdirectory(test_form)
add_subdirectory(texture_compressor_test)
add_subdirectory(ui)
add_subdirectory(vfs)
add_subdirectory(vfs_pack)
add_subdirectory(wpf_controls)
add_subdirectory(editor)
add_subdirectory(stalker2)
#add_subdirectory(xbox_debug_client)
