project(vfs LANGUAGES CXX)

add_library(vfs STATIC
					# core
					"${CMAKE_CURRENT_SOURCE_DIR}/library_linkage.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/pch.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/pch.h"
					# include
					"${CMAKE_CURRENT_SOURCE_DIR}/../api.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/../base_node.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/../base_node_inline.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/../engine.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/../find_results.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/../hashset.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/../library_linkage.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/../mount_args.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/../mount_history.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/../mount_ptr.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/../mounter_base.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/../pack_archive.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/../patch_args.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/../saving_fat_inline_data.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/../scheduled_to_unmount.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/../types.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/../unpack.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/../virtual_file_system.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/../world.h"
					# iterator
					"${CMAKE_CURRENT_SOURCE_DIR}/../iterator.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/../locked_iterator.h"
					# misc
					"${CMAKE_CURRENT_SOURCE_DIR}/../device_file_system.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/../platform_configuration.h"
					# watcher
					"${CMAKE_CURRENT_SOURCE_DIR}/../watcher.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/../watcher_notification.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/../watcher_subscriber.h"
					# finding
					"${CMAKE_CURRENT_SOURCE_DIR}/find.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/find_async.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/find_async_callbacks.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/find_async_callbacks.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/find_async_link.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/find_async_tree.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/find_environment.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/find_helper.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/find_physical.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/find_pin.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/../find_results.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/find_sub_fat.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/find_sync.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/node_lock.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/node_lock.h"
					# hashset
					"${CMAKE_CURRENT_SOURCE_DIR}/branch_locks.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/branch_locks.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/hashset.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/overlapped_node_iterator.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/overlapped_node_iterator.h"
					# iterator
					"${CMAKE_CURRENT_SOURCE_DIR}/iterator.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/locked_iterator.cpp"
					# mount
					"${CMAKE_CURRENT_SOURCE_DIR}/fat_header.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/fat_header.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/mount_archive.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/mount_archive.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/mount_archive_fixup.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/mount_args.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/mount_helper_branch.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/mount_history.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/mount_history_watcher.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/mount_hot.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/mount_lazy.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/mount_physical_path.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/mount_physical_path.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/mount_ptr.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/mount_subfat.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/mounter.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/mounter.h"
					# mount_utils
					"${CMAKE_CURRENT_SOURCE_DIR}/mount_referers.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/mount_referers.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/mount_transfer.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/mount_transfer.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/mount_utils.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/mount_utils.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/scheduled_to_unmount.cpp"
					# nodes
					"${CMAKE_CURRENT_SOURCE_DIR}/erased_node.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/external_subfat_node.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/hard_link_node.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/mount_helper_node.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/nodes.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/soft_link_node.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/universal_file_node.h"
					# archive_nodes
					"${CMAKE_CURRENT_SOURCE_DIR}/archive_compressed_file_node.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/archive_file_node.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/archive_file_node_base.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/archive_inline_compressed_file_node.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/archive_inline_file_node.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/archive_inline_file_node_base.h"
					# base_node
					"${CMAKE_CURRENT_SOURCE_DIR}/base_folder_node.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/base_folder_node_inline.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/base_node.cpp"
					# mount_root_nodes
					"${CMAKE_CURRENT_SOURCE_DIR}/archive_folder_mount_root_node.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/mount_root_node_base.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/mount_root_node_functions.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/physical_file_mount_root_node.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/physical_folder_mount_root_node.h"
					# physical_nodes
					"${CMAKE_CURRENT_SOURCE_DIR}/physical_file_node.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/physical_folder_node.h"
					# patch
					"${CMAKE_CURRENT_SOURCE_DIR}/patch.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/patch.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/patch_duplicate.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/patch_erased_nodes.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/patch_new_nodes.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/patch_utils.cpp"
					# saving
					"${CMAKE_CURRENT_SOURCE_DIR}/pack_archive.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/pack_archive_utils.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/saving.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/saving.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/../saving_args.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/saving_creating_nodes.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/saving_db.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/saving_environment.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/saving_fat_inline_data.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/saving_file.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/saving_find_duplicates.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/saving_helper.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/saving_info_tree.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/saving_info_tree.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/saving_node.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/unpack.cpp"
					# tests
					"${CMAKE_CURRENT_SOURCE_DIR}/test.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/test.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/test_find.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/test_log.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/test_mount.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/test_mount_inside.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/test_patch.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/test_utils.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/test_watcher.cpp"
					# unmount
					"${CMAKE_CURRENT_SOURCE_DIR}/free_node.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/free_node.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/unmount.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/unmount.h"
					"${CMAKE_CURRENT_SOURCE_DIR}/unmount_helper_branch.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/unmount_hot.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/unmount_inline.h"
					# watcher
					"${CMAKE_CURRENT_SOURCE_DIR}/watcher.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/watcher_notification.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/watcher_subscriber.cpp"
					# virtual_file_system
					"${CMAKE_CURRENT_SOURCE_DIR}/handle_notifications.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/virtual_file_system.cpp"
					"${CMAKE_CURRENT_SOURCE_DIR}/virtual_file_system_compare.cpp"
					# ./
)

set_target_properties(vfs PROPERTIES FOLDER "engine/core")
